clemlaf_comptes_app_homepage:
    path:  /
    defaults: { _controller: ClemLafComptesAppBundle:Main:index }

clemlaf_comptes_app_table:
    path:  /get_table
    defaults: { _controller: ClemLafComptesAppBundle:Main:get_table }

clemlaf_comptes_app_update:
    path: /update
    defaults: { _controller: ClemLafComptesAppBundle:Main:update }
    methods: POST

clemlaf_comptes_app_delete:
    path: /delete
    defaults: { _controller: ClemLafComptesAppBundle:Main:delete }

clemlaf_comptes_app_param:
    path: /param
    defaults: { _controller: ClemLafComptesAppBundle:Param:index }

clemlaf_comptes_app_delparam:
    path: /delparam
    defaults: { _controller: ClemLafComptesAppBundle:Param:delete }

clemlaf_comptes_app_period:
    path: /period
    defaults: { _controller: ClemLafComptesAppBundle:Period:index }

clemlaf_comptes_app_update_period:
    path: /period/update
    defaults: { _controller: ClemLafComptesAppBundle:Period:update }

clemlaf_comptes_app_delete_period:
    path: /period/delete
    defaults: { _controller: ClemLafComptesAppBundle:Period:delete }
