ClemLaf\ComptesAppBundle\Entity\Comptes\Periodic:
    type: entity
    table: null
    repositoryClass: ClemLaf\ComptesAppBundle\Entity\Comptes\PeriodicRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        lastDate:
            type: date
            column: last_date
        endDate:
            type: date
            column: end_date
        mois:
            type: integer
        jours:
            type: integer
        com:
            type: string
            length: 255
        prix:
            type: integer
    manyToOne:
        cpD:
            targetEntity: Compte
            inversedBy: periodsD
            joinColumn:
                name: cp_d
                referencedColumnName: id
        cpS:
            targetEntity: Compte
            inversedBy: periodsS
            joinColumn:
                name: cp_s
                referencedColumnName: id
        category:
            targetEntity: Category
            inversedBy: periodics
            joinColumn:
                 name: cat
                 referencedColumnName: id        
        moyen:
            targetEntity: Moyen
            inversedBy: periodics
            joinColumn:
                name: moy
                referencedColumnName: id
    lifecycleCallbacks: {  }
