<?php

namespace ClemLaf\ComptesAppBundle\Entity\Comptes;

use Doctrine\ORM\EntityRepository;

/**
 * EntreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntreeRepository extends EntityRepository
{
    public function getSolde($compte,$entree,$pointage=null){
	$em=$this->getEntityManager();
	$param=$pointage?
		array('nom'=> $compte):
		array(
	    'nom'=> $compte, 
	    'dd' => $entree->getDate(), 
	    'id' => $entree->getId()
		);
	$solde=$em->createQuery(
	    'SELECT SUM(e.pr) as sol '.
	    'FROM ClemLafComptesAppBundle:Comptes\Entree e '.
	    'WHERE e.cpS=:nom'.
	    ($pointage?' AND e.poS=1':' AND e.date<=:dd AND e.id<=:id')
	)
	->setParameters($param)
	->getSingleScalarResult();
	$solde=$solde-$em->createQuery(
	    'SELECT SUM(e.pr) as sol '.
	    'FROM ClemLafComptesAppBundle:Comptes\Entree e '.
	    'WHERE e.cpD=:nom'.
	    ($pointage?' AND e.poD=1':' AND e.date<=:dd AND e.id<=:id')
	)
	    ->setParameters($param)
	    ->getSingleScalarResult();
	return $solde; 
    }
}
